PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://ex.org/>


# construct new triplets of dates and corresponding job position titles which were posted on those days (dataset:Glassdoor reviews)
CONSTRUCT {
  ?date ex:job_title ?title.
}
WHERE {
  ?review rdf:type ex:review ;
		ex:date ?date;
		ex:job_title ?title.
} LIMIT 10
