PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://ex.org/>


# check whether Apple is also in the reviewed companies (dataset:Glassdoor reviews)
ASK
WHERE {
  ?company rdf:type ex:company ;
		ex:name "Apple"@en
} LIMIT 10
